### ISSUE TITLE
Kira 1.0 installation (Error: Calling <<-EOS.undent is disabled!)

### ISSUE THREAD

**Issue by raydsameshima** [tueda/homebrew-loops#8]
Dear Ueda-san,

When I tried to use your kira's formula, I faced the following error message.

Ubuntu 16.04 LTS

==> make install
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/home/ray/.linuxbrew/Library/Taps/tueda/homebrew-loops/kira.rb:33:in `caveats'
Please report this to the tueda/loops tap!
Or, even better, submit a PR to fix it!

**Comment by tueda** [comment]
Fixed by https://github.com/tueda/homebrew-loops/pull/9.
